# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2d71ee05a0e8111ef673c766edb276d98df7f75a9f56af9b1332f5298a6477c41a94d86fe80800b80ff0b5f9077f2dbd6a45a6c3396b70e6adc9ca96f21ac243

test:
  secret_key_base: b6129e3713c46fa2db3cf0edad506d3b67ff1a09508b508f37d2ad2379c0c441e6615693071c812fda4d3cd2a1381edd98e5f0d1a45bcf954bf1f055de6df17d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
